# Use a Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy only package files first (for caching)
COPY package*.json ./

# Install dependencies inside the container
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the app runs on
EXPOSE 5170

# Start the application in development mode
CMD ["npm", "run", "dev", "--", "--host"]
