services:
  mongodb:
    image: mongo:latest
    container_name: formease-mongodb-dev
    user: root
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  mongodb_data:
